# Credenciales de Supabase
SUPABASE_URL = "https://csfqduhntlqtmycdnaja.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZnFkdWhudGxxdG15Y2RuYWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Njg4NTksImV4cCI6MjA2NzE0NDg1OX0.K4Pz34uOh6GwPiF47C62daZW8OLMt5aCEWffyJPqCgc"